### PR TITLE
Updated Exec List

### PR DESCRIPTION
**Pull request by q-horton**
Updated to include the 2024 exec list and include updates from throughout 2023. Also removed the event-history document as this format has not proven very helpful in any way and only benefits those who already have this data.

### CODE REVIEW

**Review by ThatSealgair — CHANGES_REQUESTED** [review]
Don't worry about when people resigned, we haven't kept track of that in the past.

**Comment by q-horton** [comment]
@ThatSealgair update has been made to keep the record consistent.

**Review by Rapture2010 — APPROVED** [review]
Looks good to me

**Comment by q-horton** [comment]
@ThatSealgair you'll have to approve before this can get merged

**Comment by ThatSealgair** [comment]
Looks good!

**Review by ThatSealgair — APPROVED** [review]

**Pull request merged**
