### PR TITLE
Introduce Life Membership

### PR DESCRIPTION
**Pull request by q-horton**
One of the goals of our exec team this year has been to rediscover the club's history and try to re-engage with those who have come before us. I believe that this is important for the club, as it helps us to learn from the past as well as keep a strong network with alumni who might be interested in supporting members. A potential solution to help address this that I have seen been successful in other clubs is the idea of life members. The goal of this would be to honour those that have been influential in MARS' history and since demonstrated a continued commitment and support of the club.

### CODE REVIEW

**Comment by q-horton** [comment]
Would discuss changing the wording in 27.3 from "years" to "calendar years" to address cases where AGMs are aligned such that not quite two years has elapsed between the present AGM and the one two years prior.

**Review by ThatSealgair — APPROVED** [review]
Approved as per paid member voting majority during the 2023 AGM.

**Review by Rapture2010 — APPROVED** [review]
Approved as per paid member voting majority during the 2023 AGM.

**Comment by q-horton** [comment]
Will need to be reconfirmed at the 2024 AGM

**Pull request merged**
